INSERT INTO permissions (code, name, module, description)
VALUES
    ('ADMIN_ACCESS', 'Admin API access', 'ADMIN', 'Access protected administrative API endpoints'),
    ('USER_MANAGE', 'Manage users', 'ADMIN', 'Create, update, lock, unlock, reset, and soft-delete user accounts'),
    ('ROLE_MANAGE', 'Manage system roles', 'ADMIN', 'Assign and revoke system roles for users'),
    ('AUDIT_READ', 'Read audit logs', 'ADMIN', 'View system audit log records'),
    ('LOGIN_HISTORY_READ', 'Read login history', 'ADMIN', 'View login history records'),
    ('LAB_CONTENT_MANAGE', 'Manage lab content', 'CONTENT', 'Manage lab-wide content and announcements'),
    ('PROJECT_VIEW_PUBLIC', 'View public projects', 'PROJECT', 'View public project information'),
    ('PROJECT_VIEW_INTERNAL', 'View internal project content', 'PROJECT', 'View internal project information when scoped access allows it'),
    ('PROJECT_MANAGE_ALL', 'Manage all projects', 'PROJECT', 'Create, edit, and delete projects across the lab'),
    ('PROJECT_MANAGE_ASSIGNED', 'Manage assigned projects', 'PROJECT', 'Edit projects assigned to the current leader'),
    ('PROJECT_JOIN_REQUEST_CREATE', 'Create project join requests', 'PROJECT', 'Request to join public projects'),
    ('PROJECT_JOIN_REQUEST_REVIEW', 'Review project join requests', 'PROJECT', 'Approve or reject join requests for assigned projects'),
    ('PROJECT_MEMBER_MANAGE', 'Manage project members', 'PROJECT', 'Manage member lists for assigned projects'),
    ('TASK_MANAGE_ASSIGNED_PROJECT', 'Manage assigned project tasks', 'TASK', 'Create, assign, update, and review tasks for assigned projects'),
    ('TASK_VIEW_ASSIGNED', 'View assigned tasks', 'TASK', 'View tasks assigned to the current member'),
    ('TASK_SUBMIT_OUTPUT', 'Submit task output', 'TASK', 'Submit outputs or reports for assigned tasks'),
    ('EVALUATION_CREATE_ASSIGNED_PROJECT', 'Evaluate project members', 'EVALUATION', 'Evaluate members in assigned projects'),
    ('EVALUATION_VIEW_OWN', 'View own evaluations', 'EVALUATION', 'View evaluations and feedback for the current member'),
    ('POST_CREATE', 'Create posts', 'CONTENT', 'Create blog posts or shared content'),
    ('POST_SUBMIT_REVIEW', 'Submit posts for review', 'CONTENT', 'Submit draft posts into the moderation workflow'),
    ('POST_MODERATE', 'Moderate posts', 'CONTENT', 'Approve, reject, or request revisions for submitted posts'),
    ('POST_PUBLISH_LAB', 'Publish lab-wide posts', 'CONTENT', 'Publish lab-wide announcements and public lab content'),
    ('POST_PUBLISH_PROJECT', 'Publish project posts', 'CONTENT', 'Publish announcements scoped to assigned projects'),
    ('NOTIFICATION_VIEW_OWN', 'View own notifications', 'NOTIFICATION', 'View notifications addressed to the current user'),
    ('NOTIFICATION_MANAGE_OWN', 'Manage own notifications', 'NOTIFICATION', 'Mark as read or delete own notifications'),
    ('CALENDAR_MANAGE_LAB', 'Manage lab calendar', 'CALENDAR', 'Create and manage lab-wide calendar events'),
    ('CALENDAR_MANAGE_ASSIGNED_PROJECT', 'Manage assigned project calendar', 'CALENDAR', 'Create and manage calendar events for assigned projects'),
    ('FILE_MANAGE_ALL', 'Manage all files', 'FILE', 'Manage all lab, project, document, and report files'),
    ('FILE_MANAGE_ASSIGNED_PROJECT', 'Manage assigned project files', 'FILE', 'Manage files for assigned projects'),
    ('FILE_MANAGE_OWN_UPLOAD', 'Manage own uploaded files', 'FILE', 'Edit or delete own uploaded files when scoped access allows it')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    module = EXCLUDED.module,
    description = EXCLUDED.description;

WITH role_permission_codes(role_code, permission_code) AS (
    VALUES
        ('SUPER_ADMIN', 'ADMIN_ACCESS'),
        ('SUPER_ADMIN', 'USER_MANAGE'),
        ('SUPER_ADMIN', 'ROLE_MANAGE'),
        ('SUPER_ADMIN', 'AUDIT_READ'),
        ('SUPER_ADMIN', 'LOGIN_HISTORY_READ'),
        ('SUPER_ADMIN', 'LAB_CONTENT_MANAGE'),
        ('SUPER_ADMIN', 'PROJECT_VIEW_PUBLIC'),
        ('SUPER_ADMIN', 'PROJECT_VIEW_INTERNAL'),
        ('SUPER_ADMIN', 'PROJECT_MANAGE_ALL'),
        ('SUPER_ADMIN', 'PROJECT_MANAGE_ASSIGNED'),
        ('SUPER_ADMIN', 'PROJECT_JOIN_REQUEST_CREATE'),
        ('SUPER_ADMIN', 'PROJECT_JOIN_REQUEST_REVIEW'),
        ('SUPER_ADMIN', 'PROJECT_MEMBER_MANAGE'),
        ('SUPER_ADMIN', 'TASK_MANAGE_ASSIGNED_PROJECT'),
        ('SUPER_ADMIN', 'TASK_VIEW_ASSIGNED'),
        ('SUPER_ADMIN', 'TASK_SUBMIT_OUTPUT'),
        ('SUPER_ADMIN', 'EVALUATION_CREATE_ASSIGNED_PROJECT'),
        ('SUPER_ADMIN', 'EVALUATION_VIEW_OWN'),
        ('SUPER_ADMIN', 'POST_CREATE'),
        ('SUPER_ADMIN', 'POST_SUBMIT_REVIEW'),
        ('SUPER_ADMIN', 'POST_MODERATE'),
        ('SUPER_ADMIN', 'POST_PUBLISH_LAB'),
        ('SUPER_ADMIN', 'POST_PUBLISH_PROJECT'),
        ('SUPER_ADMIN', 'NOTIFICATION_VIEW_OWN'),
        ('SUPER_ADMIN', 'NOTIFICATION_MANAGE_OWN'),
        ('SUPER_ADMIN', 'CALENDAR_MANAGE_LAB'),
        ('SUPER_ADMIN', 'CALENDAR_MANAGE_ASSIGNED_PROJECT'),
        ('SUPER_ADMIN', 'FILE_MANAGE_ALL'),
        ('SUPER_ADMIN', 'FILE_MANAGE_ASSIGNED_PROJECT'),
        ('SUPER_ADMIN', 'FILE_MANAGE_OWN_UPLOAD'),
        ('ADMIN', 'ADMIN_ACCESS'),
        ('ADMIN', 'USER_MANAGE'),
        ('ADMIN', 'ROLE_MANAGE'),
        ('ADMIN', 'AUDIT_READ'),
        ('ADMIN', 'LOGIN_HISTORY_READ'),
        ('ADMIN', 'LAB_CONTENT_MANAGE'),
        ('ADMIN', 'PROJECT_VIEW_PUBLIC'),
        ('ADMIN', 'PROJECT_VIEW_INTERNAL'),
        ('ADMIN', 'PROJECT_MANAGE_ALL'),
        ('ADMIN', 'POST_MODERATE'),
        ('ADMIN', 'POST_PUBLISH_LAB'),
        ('ADMIN', 'NOTIFICATION_VIEW_OWN'),
        ('ADMIN', 'NOTIFICATION_MANAGE_OWN'),
        ('ADMIN', 'CALENDAR_MANAGE_LAB'),
        ('ADMIN', 'FILE_MANAGE_ALL'),
        ('LEADER', 'PROJECT_VIEW_PUBLIC'),
        ('LEADER', 'PROJECT_VIEW_INTERNAL'),
        ('LEADER', 'PROJECT_MANAGE_ASSIGNED'),
        ('LEADER', 'PROJECT_JOIN_REQUEST_REVIEW'),
        ('LEADER', 'PROJECT_MEMBER_MANAGE'),
        ('LEADER', 'TASK_MANAGE_ASSIGNED_PROJECT'),
        ('LEADER', 'EVALUATION_CREATE_ASSIGNED_PROJECT'),
        ('LEADER', 'POST_CREATE'),
        ('LEADER', 'POST_SUBMIT_REVIEW'),
        ('LEADER', 'POST_PUBLISH_PROJECT'),
        ('LEADER', 'NOTIFICATION_VIEW_OWN'),
        ('LEADER', 'NOTIFICATION_MANAGE_OWN'),
        ('LEADER', 'CALENDAR_MANAGE_ASSIGNED_PROJECT'),
        ('LEADER', 'FILE_MANAGE_ASSIGNED_PROJECT'),
        ('MEMBER', 'PROJECT_VIEW_PUBLIC'),
        ('MEMBER', 'PROJECT_VIEW_INTERNAL'),
        ('MEMBER', 'PROJECT_JOIN_REQUEST_CREATE'),
        ('MEMBER', 'TASK_VIEW_ASSIGNED'),
        ('MEMBER', 'TASK_SUBMIT_OUTPUT'),
        ('MEMBER', 'EVALUATION_VIEW_OWN'),
        ('MEMBER', 'POST_CREATE'),
        ('MEMBER', 'POST_SUBMIT_REVIEW'),
        ('MEMBER', 'NOTIFICATION_VIEW_OWN'),
        ('MEMBER', 'NOTIFICATION_MANAGE_OWN'),
        ('MEMBER', 'FILE_MANAGE_OWN_UPLOAD')
)
INSERT INTO role_permissions (role_id, permission_id)
SELECT roles.id, permissions.id
FROM role_permission_codes
JOIN roles ON roles.code = role_permission_codes.role_code
JOIN permissions ON permissions.code = role_permission_codes.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;
