/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as PostsSlugRouteImport } from './routes/posts_.$slug'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppPostsRouteImport } from './routes/app.posts'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppJoinRequestsRouteImport } from './routes/app.join-requests'
import { Route as AppEvaluationsRouteImport } from './routes/app.evaluations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppProjectsSlugRouteImport } from './routes/app.projects_.$slug'
import { Route as AppPostsNewRouteImport } from './routes/app.posts.new'
import { Route as AppModerationPostsRouteImport } from './routes/app.moderation.posts'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminMembersRouteImport } from './routes/app.admin.members'
import { Route as AppAdminLabRouteImport } from './routes/app.admin.lab'
import { Route as AppPostsPostIdEditRouteImport } from './routes/app.posts_.$postId.edit'
import { Route as AppModerationPostsPostIdRouteImport } from './routes/app.moderation.posts_.$postId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts_/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRequestsRoute = AppJoinRequestsRouteImport.update({
  id: '/join-requests',
  path: '/join-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationsRoute = AppEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPostsRoute,
} as any)
const AppModerationPostsRoute = AppModerationPostsRouteImport.update({
  id: '/moderation/posts',
  path: '/moderation/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLabRoute = AppAdminLabRouteImport.update({
  id: '/admin/lab',
  path: '/admin/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts_/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationPostsPostIdRoute =
  AppModerationPostsPostIdRouteImport.update({
    id: '/moderation/posts_/$postId',
    path: '/moderation/posts/$postId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/posts': typeof PostsRoute
  '/projects': typeof ProjectsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/tasks': typeof AppTasksRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/app/admin/lab': typeof AppAdminLabRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/moderation/posts': typeof AppModerationPostsRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/projects/$slug': typeof AppProjectsSlugRoute
  '/app/moderation/posts/$postId': typeof AppModerationPostsPostIdRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/posts': typeof PostsRoute
  '/projects': typeof ProjectsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/tasks': typeof AppTasksRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/app/admin/lab': typeof AppAdminLabRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/moderation/posts': typeof AppModerationPostsRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/projects/$slug': typeof AppProjectsSlugRoute
  '/app/moderation/posts/$postId': typeof AppModerationPostsPostIdRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/posts': typeof PostsRoute
  '/projects': typeof ProjectsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/join-requests': typeof AppJoinRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/tasks': typeof AppTasksRoute
  '/posts_/$slug': typeof PostsSlugRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/app/admin/lab': typeof AppAdminLabRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/moderation/posts': typeof AppModerationPostsRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/projects_/$slug': typeof AppProjectsSlugRoute
  '/app/moderation/posts_/$postId': typeof AppModerationPostsPostIdRoute
  '/app/posts_/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/posts'
    | '/projects'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/evaluations'
    | '/app/join-requests'
    | '/app/notifications'
    | '/app/posts'
    | '/app/projects'
    | '/app/tasks'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/app/admin/lab'
    | '/app/admin/members'
    | '/app/admin/users'
    | '/app/moderation/posts'
    | '/app/posts/new'
    | '/app/projects/$slug'
    | '/app/moderation/posts/$postId'
    | '/app/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/posts'
    | '/projects'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/evaluations'
    | '/app/join-requests'
    | '/app/notifications'
    | '/app/posts'
    | '/app/projects'
    | '/app/tasks'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/app/admin/lab'
    | '/app/admin/members'
    | '/app/admin/users'
    | '/app/moderation/posts'
    | '/app/posts/new'
    | '/app/projects/$slug'
    | '/app/moderation/posts/$postId'
    | '/app/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/posts'
    | '/projects'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/evaluations'
    | '/app/join-requests'
    | '/app/notifications'
    | '/app/posts'
    | '/app/projects'
    | '/app/tasks'
    | '/posts_/$slug'
    | '/projects_/$slug'
    | '/app/admin/lab'
    | '/app/admin/members'
    | '/app/admin/users'
    | '/app/moderation/posts'
    | '/app/posts/new'
    | '/app/projects_/$slug'
    | '/app/moderation/posts_/$postId'
    | '/app/posts_/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PostsRoute: typeof PostsRoute
  ProjectsRoute: typeof ProjectsRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$slug': {
      id: '/posts_/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts': {
      id: '/app/posts'
      path: '/posts'
      fullPath: '/app/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/join-requests': {
      id: '/app/join-requests'
      path: '/join-requests'
      fullPath: '/app/join-requests'
      preLoaderRoute: typeof AppJoinRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluations': {
      id: '/app/evaluations'
      path: '/evaluations'
      fullPath: '/app/evaluations'
      preLoaderRoute: typeof AppEvaluationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects_/$slug': {
      id: '/app/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/app/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts/new': {
      id: '/app/posts/new'
      path: '/new'
      fullPath: '/app/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppPostsRoute
    }
    '/app/moderation/posts': {
      id: '/app/moderation/posts'
      path: '/moderation/posts'
      fullPath: '/app/moderation/posts'
      preLoaderRoute: typeof AppModerationPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/admin/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lab': {
      id: '/app/admin/lab'
      path: '/admin/lab'
      fullPath: '/app/admin/lab'
      preLoaderRoute: typeof AppAdminLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts_/$postId/edit': {
      id: '/app/posts_/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/app/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moderation/posts_/$postId': {
      id: '/app/moderation/posts_/$postId'
      path: '/moderation/posts/$postId'
      fullPath: '/app/moderation/posts/$postId'
      preLoaderRoute: typeof AppModerationPostsPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPostsRouteChildren {
  AppPostsNewRoute: typeof AppPostsNewRoute
}

const AppPostsRouteChildren: AppPostsRouteChildren = {
  AppPostsNewRoute: AppPostsNewRoute,
}

const AppPostsRouteWithChildren = AppPostsRoute._addFileChildren(
  AppPostsRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEvaluationsRoute: typeof AppEvaluationsRoute
  AppJoinRequestsRoute: typeof AppJoinRequestsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPostsRoute: typeof AppPostsRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppAdminLabRoute: typeof AppAdminLabRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppModerationPostsRoute: typeof AppModerationPostsRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
  AppModerationPostsPostIdRoute: typeof AppModerationPostsPostIdRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEvaluationsRoute: AppEvaluationsRoute,
  AppJoinRequestsRoute: AppJoinRequestsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPostsRoute: AppPostsRouteWithChildren,
  AppProjectsRoute: AppProjectsRoute,
  AppTasksRoute: AppTasksRoute,
  AppAdminLabRoute: AppAdminLabRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppModerationPostsRoute: AppModerationPostsRoute,
  AppProjectsSlugRoute: AppProjectsSlugRoute,
  AppModerationPostsPostIdRoute: AppModerationPostsPostIdRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PostsRoute: PostsRoute,
  ProjectsRoute: ProjectsRoute,
  PostsSlugRoute: PostsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
